
name: Accessibility check (Pa11y)

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  pa11y:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pa11y
        run: npm install -g pa11y pa11y-ci

      - name: Build site
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.in
          jupyter-book build .

      - name: Run pa11y-ci on homepage
        run: |
          # Check the built homepage for common accessibility issues
          pa11y-ci --sitemap false "_build/html/index.html" || true
